version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 165536
        hard: 165536
    ports:
      - '9200:9200'
      - '9300:9300'
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'
  thehive:
    #image: thehiveproject/thehive:latest
    image: thehiveproject/thehive4:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    command: --cortex-port 9001
    volumes:
        - ./application.conf:/etc/thehive/application.conf

